sudo: false

language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - yarn eslint

deploy:
  provider: pages
  skip_cleanup: true
  # local_dir: dist
  github_token: $travis_token
  keep_history: true
  # target_branch: gh-pages
  on:
    branch: master
