sudo: false

language: node_js

node_js:
  - 'stable'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

before_install:
  - $ npm install -g cnpm --registry=https://registry.npm.taobao.org
  # - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - cnpm install

script:
  - cnpm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $travis_token
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
